### PR TITLE
Development

### PR DESCRIPTION
**Pull request by rvvergara**
Please check README for project information

### CODE REVIEW

**Comment by talihomz** [comment]
Hi @dipto0321 @rvvergara.

Great Battleship implementation! I was able to run and play the game on my machine, great work!

I have a few queries about your codebase:
1. It is really hard to understand your code files. And I do not mean syntax  (your methods and modules are really well written actually!). But I could not follow the general structure, especially for some specific files such as the [callbacks file](https://github.com/rvvergara/battleship/blob/development/src/js/utils/callbacks.js). Why are callbacks in a separate file? Shouldn't they be part of the file they are used? The challenge here is that, when an event listener is created in your project, I have to open this file to see what gets called when the event is fired (as opposed to seeing the callback in the file where the listener exists).
2. The `ship creation` util doesn't look too different from the `game display` util. They both add a bunch of listeners to the DOM. Could they be one file? Maybe you could let me know why they are split.
3. The `util\util` file combines game logic with DOM operations that should probably be in the `gameDisplay` util.
4. There should probably be only one Util that manages the DOM, though I see alot of code within separate util files that accesses the DOM, adds listeners etc.

**Comment by rvvergara** [comment]
Hi Kev (@talihomz),

Thanks man for the review. It took a while for us to get back to this project because of React learning. Please aid us in fulfilling your suggestions:

1. Grouping files is actually one of the things we haven't really mastered. Please suggest a best-practice structure that we can follow. For instance, in this case what we did was put al the event callbacks in a separate file as that was what we thought was logical. The events themselves that use these callback methods are in their own files. 
2. Re: gameDisplay.js -> @dipto0321  can probably answer this.. He's the display guru :) But in all seriousness we will refactor this accordingly.
3. Re: utils/util.js file -> Yeah I agree.. We will transfer the code in here into the gameDisplay.js file. We separated it for our sanity's sake. The functions in gameDisplay just have something to do with creating the main html elements themselves while the util.js files have something to do with what happens in ships and the game during game run. But yeah you're right util.js is related to display. What if we just create a folder called domUtils/ and just place there gameDisplay.js and utils.js so that it still is logical enough? That way we avoid having a single bloated file. Is that a good idea?
4. Same thing as 3 above.

Thanks Kev!

**Comment by dipto0321** [comment]
Hi @talihomz ,
As you said `ship_creation` util and `game_display` is different. In `game_display` we only generate all the necessary things for only create the game board. But in ship creation until First according to back-end logic, it creates the ships and then places those ship into their own position. SO I think it's okay to be separate 😄 
Thanks 🙏

**Comment by talihomz** [comment]
@rvvergara @dipto0321 Aah ok, this makes sense now. The challenge is, the code should be self explanatory and intuitive. You won't always be in a position to explain to the reader when they need to add features or modify existing ones.
This was one of the challenging projects, and I think you did a good job on it overall!

Its a :+1: from me.

PS: We can have a one on one zoom call and discuss some design ideas around folder structures that might be of use.

**Comment by rvvergara** [comment]
Thanks @talihomz, 

Cool! We would love that!

**Pull request merged**
